### ISSUE TITLE
Possible to flash with raspberry pi?

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [pedroke/ZigWaterMeter#1]
hey pedro. 

I try to find a way to contact you but did not find a email or something like this.

Awesome project here. But I had some question marks before I really can start with it.
A programmer is quite expensive but I've heard that it is possible to flash it with a raspberry pi. Is this possible with your precompiled hex too?

**Comment by pedroke** [comment]
Hi, the programmer can be bought from aliexpress and it is very cheap. But you can flash it also by rpi..
