### ISSUE TITLE
How to store network related stuff to NVRAM?

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [pedroke/ZigWaterMeter#2]
I had no clue it works to connect  a ZigWaterMeter device to my zigbee network.

It written something like "network related stuff is stored in NVRAM". But how get it into this?

**Comment by pedroke** [comment]
When device is started for the first time, it joins the available network automatically and then stores network related stuff to its NVRAM.. no user interaction needed.

**Comment by sorryusernameisalreadytaken** [comment]
Awesome. Thanks for the reply.
